# Read the documentation at https://github.com/thephpleague/flysystem-bundle/blob/master/docs/1-getting-started.md
flysystem:
    storages:
        default.storage:
            adapter: 'local'
            options:
                directory: '../../../../Apps/MultiMC/instances/SymfonyCon/.minecraft/saves/SymfonyCon 2019/generated/minecraft/structures'
